import { Component } from '@angular/core';

import { NavController, ModalController } from 'ionic-angular';
import { SpeakerDetailsPage } from '../speaker-details/speaker-details';

@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})
export class HomePage {
  public speakers: any[] = [];

  constructor(public navCtrl: NavController, public modalCtrl: ModalController) {
    this.speakers.push({ name: 'Walmyr Carvalho', title: '99, São Paulo, Brasil', image: 'assets/images/walmyr.jpg', bio: 'Desenvolvedor Android e designer nascido em Brasília, mas atualmente vivendo em São Paulo, SP. Trabalha com Android há mais de 6 anos e sempre busca fazer o seu trabalho com excelência técnica em desenvolvimento e design. Já trabalhou em projetos para empresas como Hotel Urbano, Globo.com, CI&T, Google e atualmente trabalha na 99. Além do trabalho, é bastante ativo em comunidades e acredita que todo conhecimento deve ser compartilhado. É organizador do Android Meetup Rio de Janeiro, Kotlin Meetup São Paulo e do Android Dev BR, a maior comunidade brasileira de Android no Slack, com mais de 2000 membros. Além disso, costuma palestrar e participar de conferências e tenta retribuir a comunidade o máximo possível.' });
    this.speakers.push({ name: 'Leonardo Saraiva', title: 'Beauty Date, Campo Mourão, Brasil', image: 'assets/images/leonardo.jpg', bio: 'Co-fundador do GURU-PR e do WSO2 Brasil! Organizador do Tech Day, que ocorre anualmente em Curitiba. Desenvolvedor louco por tecnologia, atualmente surfando na onda de ruby, rails, hanami, go, grpc, docker, microserviços e kubernetes. Mas com experiência em sinatra, python (django), java, c# e um pouco de tudo, mas já não tão ativamente.' });
    this.speakers.push({ name: 'Cynthia Zanoni', title: 'Microsoft, São Paulo, Brasil', image: 'assets/images/cynthia.jpg', bio: 'Evangelista Técnica na Microsoft, curadora da Mobile Summit Brazil e idealizadora do WoMakersCode, um projeto focado em capacitação e empoderamento feminino e de minorias na TI e atua, também, como coordenadora do WoMoz (Women & Mozilla). É apaixonada open source e nas horas vagas, cria projetos e iniciativas que possam contribuir para o fortalecimento das mulheres no mercado de trabalho e comunidades de tecnologia.' });
    this.speakers.push({ name: 'Angelo Belchior', title: 'ESX - entrega contínua de valor, São Paulo, Brasil', image: 'assets/images/angelo.png', bio: 'Angelo Belchior é desenvolvedor há quase 15 anos tendo participado de projetos Desktop, Web e agora Mobile utilizando Xamarin. É Microsoft MVP em Visual Studio and Technologies, MCPD em Web e é Lead Software Developer na ESX' });
    this.speakers.push({ name: 'Matheus Costa Vieira', title: 'CINQ Technologies, Curitiba, Brasil', image: 'assets/images/matheus_costa.jpg', bio: 'Casado com a Daniela e pai do Pedro Henrique. Bacharel em Sistemas de Informação pela Universidade Positivo, pós-graduado em Engenharia E Aarquitetura DE Software pela Universidade Estácio de Sá, pós-graduando em Sistemas Embarcados e Internet das Coisas pela Univerdade Positivo. Mais de 9 anos de experiência com desenvolvimento de software com passagem em diversos tipos de projetos (e-commerce, rastreamento de veículos, ERP, sistemas de mensagens de aviação comercial). Trabalho com desenvolvimento Web, Desktop e Mobile. Esse semestre inicei na carreira de docência lecionando as disciplinas de Desenvolvimento Web e Programação Visual na Faculdade Opet' });
    this.speakers.push({ name: 'Joselito Júnior', title: 'Tampa Works, Recife, Brasil', image: 'assets/images/joselito.jpg', bio: 'Organizador do GDG Recife e do devbeers, podcaster no Code Talks, instrutor dos Ionic Bootcamp e fundador das startups premiadas Estudorama e Rabiscapp. Além de ganhador de Hackathons aposentado, é entusiasta do Design Thinking, Lean Startup e desenvolvimento Ágil de software. Fã de Fórmula 1 e de fazer piadas de gosto duvidoso.' });
    this.speakers.push({ name: 'Loiane Groner', title: 'Citi e loiane.training, São Paulo, Brasil', image: 'assets/images/loiane.jpg', bio: 'Possui 10+ anos de experiência em TI, trabalha como desenvolvedora FullStack em uma empresa multinacional e ama compartilhar conhecimento! Já palestrou por vários eventos no Brasil e ministrou cursos nos Estados Unidos. Autora dos livros: Ext JS 4 First Look, Mastering Ext J(primeira e segunda edição), Sencha Architect App Development e Learning JavaScript Data Structures and Algorithms (primeira e segunda edição), JavaScript Regular Expressions - todos publicados pela editora Packt e lançados mundialmente em inglês (com tradução de alguns livros para chinês e coreano). Espera poder lançar livros em Português em breve. Entusiasta Java, Sencha, Angular e mobile híbrido (Phonegap/Ionic). Participa ativamente dessas comunidades. Escreve para o blog http://loiane.com e publica aulas e cursos em http://loiane.training.' });
    this.speakers.push({ name: 'Lazaro Fernandes', title: 'Lambda3, São Paulo, Brasil', image: 'assets/images/lazaro.jpg', bio: 'Formado em Ciências da Computação e com pós-graduação em Desenvolvimento de Produtos e Serviços pela FIA, possui 10 anos de experiência em desenvolvimento web, participa de eventos, podcasts e meetups da área ajudando na divulgação de novas tecnologias' });
    this.speakers.push({ name: 'Neto Marin', title: 'Google, São Paulo, Brasil', image: 'assets/images/NetoMarin.png', bio: 'Neto Marin é Developer Advocate do Google no Brasil e tem como principal objetivo ajudar os desenvolvedores a criarem aplicativos de alta qualidade para as plataformas Android. Um apaixonado pelas tecnologias móveis, começou a desenvolver para telefones celulares em 2005 com Java ME, tendo experiência em diversas outras plataformas e trabalhando com Android desde os primeiros SDKs em 2007. Desde 2010 vem se aventurando no mundo de softwares embarcados e pequenos dispositivos conectados como hobby, e agora está envolvido com a nova plataforma de IoT do Google, o Android Things. Neto também é um dos hosts do podcast Dev & Community Cast, que tem episódios sobre comunidades e desenvolvimento, além da série Faaala, Neto! onde compartilha suas experiências e pensamentos sobre o desenvolvimento de software.' });
    this.speakers.push({ name: 'Danilo Gonçalves', title: 'EBANX, Curitiba, Brasil', image: 'assets/images/danilo.png', bio: 'Arquiteto de Software no EBANX, rubista de longa data, nerd de carteirinha e eterno estudante. Trabalhando como desenvolvedor por mais de metade de sua existência, adquiriu experiência em diversas linguagens e tecnologias e deixou um rastro de novos rubistas por onde passou. Entusiasta da programação funcional, mais recentemente da linguagem Elixir, busca constantemente trazer novos membros para o lado imutável da força.' });
    this.speakers.push({ name: 'Luis Leão', title: 'Udacity, São Paulo, Brasil', image: 'assets/images/walmyr.jpg', bio: 'Course Manager na Udacity, co-organiza o Google Developer Group de São Paulo e atua em diversas áreas voltadas para empreendedorismo e inovação, entre eles é responsável por um grupo de estudo de Internet das Coisas (IoT) no RedBull Station e pelo programa Startup in School, projeto de formação empreendedora e programação para estudantes de escolas públicas.' });
    this.speakers.push({ name: 'Marcelo Ricardo Quinta', title: 'UFG, Goiânia, Brasil', image: 'assets/images/quinta.jpg', bio: 'Desenvolvedor móvel há mais de 10 anos, professor, pesquisador, Google Expert, Intel Innovator, mentor de startups para o Google.' });
    this.speakers.push({ name: 'André Baltieri', title: 'balta.io, São Paulo, Brasil', image: 'assets/images/baltieri.jpg', bio: 'Microsoft MVP desde 2013, trabalha com aplicações Web desde 2013 tendo atuado em projetos de pequeno, médio e grande porte no Brasil e Estados Unidos. Apesar do grande vínculo com a Microsoft, é amante das tecnologias Open Source, onde atua boa parte do tempo. Atualmente trabalha com consultorias e treinamentos, tendo passado por inúmeras empresas no Brasil, e é CIO da plataforma de cursos online, balta.io.' });
    this.speakers.push({ name: 'Ângelo Polotto', title: 'Radek Systems, Curitiba, Brasil', image: 'assets/images/polotto.jpg', bio: 'Graduado em Engenharia Eletrônica pela Universidade Tecnológica Federal do Paraná, possui interesse em desenvolvimento de software voltado para dispositivos móveis e embarcados. Trabalha atualmente com desenvolvimento para Android e iOS utilizando a ferramenta Xamarin e a linguagem C#.' });
    this.speakers.push({ name: 'Matheus Donizete', title: 'StrikeXII Development, Curitiba, Brasil', image: 'assets/images/matheus.jpg', bio: 'Entusiasta JavaScript, cursando Ciência da Computação pela UFPR, desenvolvedor JavaScript há 5 anos, em paralelo trabalhando com diversas linguagens back-end, por vezes com desenvolvimento móvel, porém sempre no cenário front-end. Atualmente trabalhando com aplicações Full-Stack feitas em JavaScript, voltado a aplicações em tempo real.' });
    this.speakers.push({ name: 'Marcos Hitanael Barchiki dos Santos', title: 'RouteSmart, Curitiba, Brasil', image: 'assets/images/marcos.jpg', bio: 'Sou desenvolvedor, empreendedor, nerd e maker. CEO na RouteSmart e 100% focado em soluções inovadoras. Fundador da Comunidade CocosSharp Brasil e membro do CodeFor Curitiba. Fã de C#, PHP e Hackathons OpenSource. Entusiasta de Xamarin, Games, IoT e realidade Virtual.' });
    this.speakers.push({ name: 'Leandro Prado', title: 'Microsoft, São Paulo, Brasil', image: 'assets/images/leandro.png', bio: 'Leandro Prado é graduado em Sistemas de Informação pela PUC-PR, trabalho com desenvolvimento desde 2003 e nos últimos anos tenho trabalhado com Visual Studio e TFS. Atualmente trabalha como Premier Field Engineer na Microsoft especializado em DevOps e ALM. Fanático por futebol e torcedor do melhor time do paraná – COXA' });
  }

  showDetails(data: any) {
    let modal = this.modalCtrl.create(SpeakerDetailsPage, { speaker: data });
    modal.present();
  }
}
